# ANN For Regression Model

## Introduction
An Artificial Neural Network (ANN) is a model inspired by how the human brain learns.
In regression problems, it predicts continuous values instead of categories.
Example:

Predicting insurance charges 💰

Predicting temperature 🌡️

Predicting exam scores

## Introduction

An Artificial Neural Network (ANN) is a model inspired by how the human brain learns.
In regression problems, it predicts continuous values instead of categories.
Example:

1.Predicting insurance charges

2.Predicting temperature

3.Predicting exam scores

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
# BASIC CHECKS

In [2]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [5]:
df.describe(include = 'O')

         sex smoker     region
count   1338   1338       1338
unique     2      2          4
top     male     no  southeast
freq     676   1064        364

# OHE (ONE HOT ENCODING)

In [6]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
region_encoded = pd.get_dummies(df["region"], prefix="region", drop_first=True)
df = pd.concat([df, region_encoded], axis=1)
df.drop("region", axis=1, inplace=True)

In [8]:
df

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,female,27.900,0,yes,16884.92400,False,False,True
1,18,male,33.770,1,no,1725.55230,False,True,False
2,28,male,33.000,3,no,4449.46200,False,True,False
3,33,male,22.705,0,no,21984.47061,True,False,False
4,32,male,28.880,0,no,3866.85520,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,10600.54830,True,False,False
1334,18,female,31.920,0,no,2205.98080,False,False,False
1335,18,female,36.850,0,no,1629.83350,False,True,False
1336,21,female,25.800,0,no,2007.94500,False,False,True
1337,61,female,29.070,0,yes,29141.36030,True,False,False

In [ ]:
# LABEL ENCODING

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])

In [ ]:
df

In [ ]:
X = df.drop('charges', axis=1)
y = df['charges']

In [ ]:
X

In [ ]:
y

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
y_train

In [ ]:
X_train.shape

In [ ]:
model = Sequential([
    Dense(120, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(1)  # Output layer (no activation for regression)
])

In [ ]:
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mse',          # Mean Squared Error for regression
    metrics=['mae']       # Mean Absolute Error as an additional metric
)

In [ ]:
history = model.fit(X_train, y_train, epochs=200, validation_split=0.2)

In [ ]:
loss, mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {mae:.2f}")

In [ ]:
from sklearn.metrics import mean_squared_error

# Get predictions
y_pred = model.predict(X_test)

# Compute MSE
mse = mean_squared_error(y_test, y_pred)
print("Test MSE:", mse)